In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

workbook = "2016-2020 Regular Season Team Stats.xlsx"

all_dfs = pd.read_excel(workbook, sheet_name = None)
df = pd.concat(all_dfs, ignore_index = True)
df.dropna(axis=1, how = "all")

,TEAM,Year,GP,W,L,MIN,OFFRTG,DEFRTG,NETRTG,AST%,AST/TO,AST,OREB%,DREB%,REB%,TOV%,EFG%,TS%,PACE,PIE
0,Atlanta Hawks,2016,82,48,34,3966,104.6,100.8,3.9,66.3,1.71,19.0,23.4,69.8,47.4,15.2,51.6,55.2,97.63,52.8
1,Boston Celtics,2016,82,48,34,3956,105.8,102.5,3.3,61.6,1.76,17.4,29.0,70.7,49.5,13.8,48.8,53.1,99.43,52.0
2,Brooklyn Nets,2016,82,21,61,3951,102.4,109.7,-7.4,58.3,1.51,17.0,27.9,71.6,49.4,15.3,49.2,52.7,96.12,46.0
3,Charlotte Hornets,2016,82,48,34,3971,106.4,103.7,2.7,58.6,1.73,16.7,24.4,75.4,49.9,12.9,50.2,54.5,96.24,51.1
4,Chicago Bulls,2016,82,42,40,3981,104.1,105.5,-1.4,59.1,1.64,17.0,29.0,71.4,50.6,14.2,48.7,52.6,96.60,49.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Sacramento Kings,2020,64,28,36,3102,109.0,110.8,-1.7,58.0,1.62,17.3,25.6,73.5,49.0,14.4,53.1,56.3,99.08,47.8
146,San Antonio Spurs,2020,63,27,36,3059,111.3,112.8,-1.5,58.4,2.00,17.9,22.8,75.1,49.1,12.1,52.9,56.9,100.60,49.8
147,Toronto Raptors,2020,64,46,18,3092,111.3,104.9,6.4,62.6,1.76,18.2,25.9,71.5,49.4,14.2,53.6,57.4,100.87,53.1
148,Utah Jazz,2020,64,41,23,3077,112.1,108.8,3.3,55.2,1.49,16.7,25.8,74.7,51.2,15.0,55.2,58.7,98.95,51.8
149,Washington Wizards,2020,64,24,40,3087,111.1,115.0,-3.9,60.4,1.80,17.8,26.0,70.8,47.6,13.5,52.8,56.8,103.52,47.8